const companies = [{
    name: 'Jman groups',
    location: 'Chennai, India',
    field: 'software',
    designation: "Full Stack developer",
    time: 'Fulltime',
    about: "JMAN is a “best of” consulting organisation, taking the best of specific disciplines and industries to deliver a unique offering that is fast, smart and useful to our client partners.",
    skills: ["React js", "Node js", "python"],
    salary: '5L',
},
{
    name: 'TCS',
    location: 'Hyderabad, India',
    field: 'sales',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'finance',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'software',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'management',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'finance',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'humanresource',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'software',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'finance',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'humanresource',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'sales',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},
{
    name: 'Infosys',
    location: 'Hyderabad, India',
    field: 'software',
    designation: "Technical trainee",
    time: 'Fulltime',
    about: "TCS, a global leader in IT services, consulting, and business solutions, leverages technology for business transformation and helps catalyze change.",
    skills: ["java", "SQL", "python"],
    salary: '4L',
},

]

export default companies;